(source-directories '("." "./sk-tests/" "../"))
(load "mktests.scm")
(load "test-skdefs.scm")
(load "test-revo.scm")
(load "test-wns.scm")
(load "test-pcs.scm")
(load "test-fgc.scm")
(load "test-syntax.scm")
